version: "3"

services:
  dynamo:
    image: trellisldp/dynamo:0.1.1
    container_name: dynamo
    restart: always
    ports:
      - "9095:9095"
    networks:
      - 110_default

networks:
  110_default:
    external: true