version: "3"

services:
  dynamo:
    image: ubleipzig/dynamo:0.3.0
    container_name: dynamo
    restart: always
    ports:
      - "9095:9095"
    networks:
      - 110_default
    environment:
        DYNAMO_HOME: /etc/dynamo
    volumes:
      - ./cfg/de.ubleipzig.dynamo.cfg:/etc/dynamo/de.ubleipzig.dynamo.cfg
  dynamo-search:
    image: ubleipzig/dynamo-search:0.3.0
    container_name: dynamo-search
    restart: always
    ports:
      - "9097:9097"
    networks:
      - 110_default
    environment:
        DYNAMO_HOME: /etc/dynamo
    volumes:
      - ./cfg/de.ubleipzig.dynamo.cfg:/etc/dynamo/de.ubleipzig.dynamo.cfg
  redis:
    image: ubleipzig/redis:latest
    container_name: redis
    ports:
      - "6379"
    networks:
      - 110_default
    volumes:
      - redis-data-volume:/data

networks:
  110_default:
    external: true

volumes:
  redis-data-volume:
    driver_opts:
      type: none
      device: /mnt/redis-data
      o: bind