version: "3"

services:
  dynamo:
    image: trellisldp/dynamo:0.2.1
    container_name: dynamo
    restart: always
    ports:
      - "9095:9095"
    networks:
      - 18_default
  dynamo-search:
    image: trellisldp/dynamo-search:0.2.1
    container_name: dynamo-search
    restart: always
    ports:
      - "9097:9097"
    networks:
      - 18_default

networks:
  18_default:
    external: true